"""Public Codito protocol API."""

from .contracts import TOOL_CONTRACTS
from .digest import canonical_action_bytes, compute_action_digest
from .envelope import MessageKind, OperationPayload, TunnelBindings, TunnelEnvelope
from .errors import ErrorCode, ToolError, ToolFailure
from .patch import (
    PatchConflict,
    PatchedFile,
    ProjectApplyPatchInput,
    ProjectApplyPatchResult,
)
from .read import (
    Continuation,
    DirectoryEntry,
    ListDirectoryInput,
    ListDirectoryResult,
    ListProjectsInput,
    ListProjectsResult,
    ProjectReadInput,
    ProjectReadResult,
    ProjectSummary,
    ReadFileInput,
    ReadFileResult,
    SearchMatch,
    SearchTextInput,
    SearchTextResult,
)
from .schemas import (
    export_schemas,
    schema_for,
    validate_project_apply_patch,
    validate_project_read,
    validate_project_shell,
)
from .shell import (
    ProjectShellInput,
    ProjectShellResult,
    ScriptCommand,
    ShellCancelInput,
    ShellCancelResult,
    ShellCommand,
    ShellOutputChunk,
    ShellPollInput,
    ShellPollResult,
    ShellStartInput,
    ShellStartResult,
    StructuredCommand,
)
from .types import PROTOCOL_VERSION, CoditoModel, OpaqueId, RelativePath, Sha256

__all__ = [
    "PROTOCOL_VERSION",
    "TOOL_CONTRACTS",
    "CoditoModel",
    "Continuation",
    "DirectoryEntry",
    "ErrorCode",
    "ListDirectoryInput",
    "ListDirectoryResult",
    "ListProjectsInput",
    "ListProjectsResult",
    "MessageKind",
    "OpaqueId",
    "OperationPayload",
    "PatchConflict",
    "PatchedFile",
    "ProjectApplyPatchInput",
    "ProjectApplyPatchResult",
    "ProjectReadInput",
    "ProjectReadResult",
    "ProjectShellInput",
    "ProjectShellResult",
    "ProjectSummary",
    "ReadFileInput",
    "ReadFileResult",
    "RelativePath",
    "ScriptCommand",
    "SearchMatch",
    "SearchTextInput",
    "SearchTextResult",
    "Sha256",
    "ShellCancelInput",
    "ShellCancelResult",
    "ShellCommand",
    "ShellOutputChunk",
    "ShellPollInput",
    "ShellPollResult",
    "ShellStartInput",
    "ShellStartResult",
    "StructuredCommand",
    "ToolError",
    "ToolFailure",
    "TunnelBindings",
    "TunnelEnvelope",
    "canonical_action_bytes",
    "compute_action_digest",
    "export_schemas",
    "schema_for",
    "validate_project_apply_patch",
    "validate_project_read",
    "validate_project_shell",
]
