# Generated by Django 5.2.17 on 2026-09-08 12:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_approved_device_reads"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="mode",
            field=models.CharField(
                choices=[
                    ("isolated", "Isolated"),
                    ("native_approval", "Native approval"),
                    ("native_trusted", "Native trusted"),
                    ("native_project", "Project access (native)"),
                ],
                default="isolated",
                max_length=24,
            ),
        ),
    ]
