# Generated by Django 5.2.17 on 2026-09-08 12:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_alter_project_mode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="operation",
            name="kind",
            field=models.CharField(
                choices=[
                    ("project_read", "Project read"),
                    ("project_apply_patch", "Project apply patch"),
                    ("project_shell", "Project shell"),
                    ("project_manage", "Project management"),
                    ("device_read", "Approved device read"),
                    ("device_screenshot", "Approved screenshot"),
                ],
                max_length=32,
            ),
        ),
    ]
